---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gypaza9q4r9s/public_html
    - /bin/cp about-us.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp our-mission.php $DEPLOYPATH
    - /bin/cp services.php $DEPLOYPATH
    - /bin/cp -R stories $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R owl-carousel $DEPLOYPATH
